### ISSUE TITLE
Index names are not unique

### ISSUE THREAD

**Issue by garvank** [Invoca/declare_schema#154]
I have a rails application using sqlite locally and postgres in production. 

#### Issue
When trying to create an index on a field, for example: "user_id on comments" and "user_id on assignments" my generated migrations are unable to run due to an error stating that "index :on_user_id already exists". 

#### STR

1. Have 3 models, for example `Comment`, `Assignment`, and `User`
2. `Comment` and `Assignement` both `belong_to :user`
3. When running the second generated migration, see the error

#### Workaround
Rename `:on_user_id` to `:user_id_on_comments` in the migration file

#### Expected Behavior
The generated migrations generate unique index names and can be run successfully

**Comment by ColinDKelley** [comment]
Thanks for letting us know about this on Postgres. It was my mistake to assume MySQL uniqueness rules (where index names are unique per table) vs having index names be globally unique. The incentive there was that MySQL has a hard limit of 64 characters for index names and we were blowing up there sometimes.

Here's an idea for a compromise:
1. Allow the max index name to be configured. Default this to 64, but you could set it to `nil` meaning unlimited, for example if you'll only be deploying to Postgres.
2. Change the [default index name generator](https://github.com/Invoca/declare_schema/blob/7a0a75966bc23c1ebd9ee3140e6303817b068f49/lib/declare_schema/model/index_definition.rb#L60-L62) to honor the configured length by trying these conventions in turn until the first is found that fits within the configured limit, if any:
- `"index_#{table_name}_on_#{column_names.join('_and_')}"`  <--- the Rails convention
- `"#{table_name}__#{column_names.join('__')}"`
- raise an exception indicating that an explicit `name:` must be chosen to stay within the configured limit

Sound good?

**Comment by ColinDKelley** [comment]
^ @garvank Sound good?

**Comment by garvank** [comment]
@ColinDKelley Configuration and docs describing them sound good to me! The other thing that comes to mind is that maybe it _must_ be configured or else raise an error.

**Comment by ColinDKelley** [comment]
@garvank I decided not to require configuration. I just default the config to 64 characters since that's what you need if you want the code to work with all possible database types. For Postgres you can set the config to `nil` if the version you're using is truly unlimited:
```ruby
DeclareSchema.max_index_and_constraint_name_length = nil
```
I've published a pre-release version with this change. Can you try it out and report back on how it works for you? The version is `declare_schema 1.3.0.colin.1`.

And here's the PR if you wouldn't mind reviewing it. This view hides whitespace changes so the indentation changes in the spec are a bit less: https://github.com/Invoca/declare_schema/pull/155/files?diff=unified&w=1

**Comment by garvank** [comment]
@ColinDKelley I was able to make a new index on user ID which was notoriously causing the issue! So far LGTM. Thanks for working on this, I love the tool. 😎

**Comment by garvank** [comment]
Just ran into a funny issue related to this. I'm using SQLite for development and postgres in production. SQLite has a limit and postgres doesn't! Ultimately I'll need to run postgres locally for development, but still a bummer. Thought I'd pass along the issue, though I don't think there's an easy answer here.

**Comment by ColinDKelley** [comment]
Can't you configure the limit to the smaller of the 2 that you use (SQLite)?

**Comment by jebentier** [comment]
@garvank It's been a while! I've taken some time this weekend to build out full PostgreSQL support into the gem. The PR is linked to this issue. I'll get a pre release up after an initial round of CR, but locally I've had some success with the changes. Let me know if there's any other issues you've found with using `declare_schema` against Postgres and I can see about squeezing fixes into this release as well.

**Comment by jebentier** [comment]
`2.1.0.pre.1` is released for testing
